#!/usr/bin/env bash

# Credit to ThePrimeagen

# Check if a project directory is provided as an argument
if [[ $# -eq 1 ]]; then
	selected="$1"
else
	# Find directories in the project path
	items=$(find ~/mnt/projects -maxdepth 1 -mindepth 1 -type d)
	items+=$(echo -e "\n/tmp")
	selected=$(echo "$items" | fzf)
fi

# Sanitize the directory name for tmux session naming
dirname=$(basename "$selected" | sed 's/\./_/g')

# Try to switch to an existing tmux session with the directory name
tmux switch-client -t "=$dirname"
if [[ $? -eq 0 ]]; then
	exit 0
fi

# Create a new tmux session or attach to an existing one
tmux new-session -c "$selected" -d -s "$dirname" && tmux switch-client -t "$dirname" || tmux new -c "$selected" -A -s "$dirname"
